src/gz base https://openwrt-23-05.vercel.app/arm_cortex-a5_neon-vfpv4/base
src/gz kmod https://openwrt-23-05.vercel.app/arm_cortex-a5_neon-vfpv4/kmod
src/gz luci https://openwrt-23-05.vercel.app/arm_cortex-a5_neon-vfpv4/luci
src/gz packages https://openwrt-23-05.vercel.app/arm_cortex-a5_neon-vfpv4/packages